balena-io/cert-manager

- entry.sh
> Allow extra keys/certs with no defaults

- Dockerfile
- certs.json
- entry.sh
- keys.json
> Refactor handling of defaults

- entry.sh
> Handle export chain on TLD changes

- entry.sh
Resolves https://github.com/balena-io/cert-manager/issues/10
This change expects that the directory containing the latest certificates would have the latest modified date.
Change-type: patch
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>
> Links to the latest public certs generated by certbot.

- entry.sh
> Fix resolve_templates function

- entry.sh
> Check if public cert is issued

- entry.sh
> Revert shellcheck recommendations

- Dockerfile
- entry.sh
> Lock critical sections

- entry.sh
> Optional balena supervisor|api

- certs.json
* VPN_HOST => cloudlink.{{tld}}
Change-type: minor
> Rebrand VPN to CloudLink

- balena.yml
> Refactor post-provisioning steps

- balena.yml
> Refactor markdown

- Dockerfile
- entry.sh
> Change env var name

- entry.sh
> Create PKI directory structure

- Dockerfile
- entry.sh
> Backup entire ACME directory

- .github/workflows/flowzone.yml
- Dockerfile
> Flowzone: use inherited secrets

- entry.sh
> Exclude accounts/hooks from backup

- entry.sh
* if a valid cert is retrieved from S3 backup, use it
Change-type: patch
> Don't hammer ACME with cert requests

- Dockerfile
- entry.sh
> Don't clobber custom certs

- entry.sh
> Allow plain TLD certs without UUID

- .github/workflows/flowzone.yml
- Dockerfile.template
- entry.sh
* assumble ca-bundle
* build GH package
* build balena multiarch
change-type: patch
> Move to balena-io

- entry.sh
> Update the links to certificates when DNS_TLD or TLD changes.

- entry.sh
.. handle situations where the chain may not already be there (init/first run).
> refactor chain cert surfacing

- entry.sh
Related: https://github.com/balena-io/environment-staging/pull/5342
* add auth. header if `AUTH_TOKEN` is defined
* shellcheck/cleanup
* refactor lower case envs. to upper
> Add CA auth. header in AUTH_TOKEN is set

- entry.sh
Requires: https://github.com/balena-io/balena-cloud/pull/4545
> patch: Handle AWS/SSO auth. flow

- entry.sh
> Request for new private cert if existing is expiring.
